part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();

  static const WELCOME = _Paths.WELCOME;
  static const HOME = _Paths.HOME;
  static const SPLASH = _Paths.SPLASH;
  static const OTP = _Paths.OTP;
  static const PHONE_ONBOARDING = _Paths.PHONE_ONBOARDING;
  static const CREATE_PIN = _Paths.CREATE_PIN;
  static const PERSONAL_INFO = _Paths.PERSONAL_INFO;
  static const SIGNIN_WITH_PIN = _Paths.SIGNIN_WITH_PIN;
  static const FORGET_PASSWORD = _Paths.FORGET_PASSWORD;
  static const HOBBIES_ONBOARDING = _Paths.HOBBIES_ONBOARDING;
  static const BRANDS_ONBOARDING = _Paths.BRANDS_ONBOARDING;
  static const RETAILERS_ONBOARDING = _Paths.RETAILERS_ONBOARDING;
  static const STYLE_ONBOARDING = _Paths.STYLE_ONBOARDING;
  static const CHAT = _Paths.CHAT;
  static const MY_DASHBOARD = _Paths.MY_DASHBOARD;
  static const VISION_BOARD = _Paths.VISION_BOARD;
  static const PROJECTS = _Paths.PROJECTS;
  static const PROJECT_DETAIL = _Paths.PROJECT_DETAIL;
  static const PROFILE = _Paths.PROFILE;
  static const NAVBAR = _Paths.NAVBAR;
  static const NEW_PROJECT = _Paths.NEW_PROJECT;
  static const CONTACT_US = _Paths.CONTACT_US;
  static const ACTIVITY = _Paths.ACTIVITY;
  static const HISTORY = _Paths.HISTORY;
  static const ACCOUNT_SETTING = _Paths.ACCOUNT_SETTING;
  static const NOTIFICATIONS = _Paths.NOTIFICATIONS;
  static const TOOL_AND_SUPPLY = _Paths.TOOL_AND_SUPPLY;
  static const PURCHASES = _Paths.PURCHASES;
  static const SEARCH_RESULT = _Paths.SEARCH_RESULT;
  static const TOOLS_AND_SUPPLIES_LIST = _Paths.TOOLS_AND_SUPPLIES_LIST;
  static const VENDOR_LIST = _Paths.VENDOR_LIST;
  static const PROJECT_INDIVIDUAL = _Paths.PROJECT_INDIVIDUAL;
  static const ONBOARDING_SUMMARY = _Paths.ONBOARDING_SUMMARY;
  static const PREFERENCES = _Paths.PREFERENCES;
  static const SIGNUP_SUCCESS = _Paths.SIGNUP_SUCCESS;
  static const CHANGE_PIN = _Paths.CHANGE_PIN;
  static const TOOLS_AND_TUTORIALS = _Paths.TOOLS_AND_TUTORIALS;
  static const INDIVIDUAL_TOOL = _Paths.INDIVIDUAL_TOOL;
  static const SELECT_LANGUAGE = _Paths.SELECT_LANGUAGE;
  static const END_USER_LICENSE = _Paths.END_USER_LICENSE;
  static const PRIVACY_POLICY = _Paths.PRIVACY_POLICY;
  static const PROJECT_STATUS = _Paths.PROJECT_STATUS;
  static const CHANGE_LANGUAGE = _Paths.CHANGE_LANGUAGE;
  static const CHANGE_COUNTRY = _Paths.CHANGE_COUNTRY;
  static const UPDATE_PIN = _Paths.UPDATE_PIN;
  static const NAVIGATION_MAP = _Paths.NAVIGATION_MAP;
  static const ORDER_DETAILS = _Paths.ORDER_DETAILS;
  static const DISPATCHERS_LIST = _Paths.DISPATCHERS_LIST;
  static const CHAT_ROOM = _Paths.CHAT_ROOM;
  static const SIGNUP = _Paths.SIGNUP;
  static const VERIFY_NFC = _Paths.VERIFY_NFC;
  static const ONBOARDING = _Paths.ONBOARDING;
}

abstract class _Paths {
  _Paths._();

  static const WELCOME = '/welcome';
  static const NAVIGATION_MAP = '/navigation-map';
  static const HOME = '/home';
  static const SPLASH = '/splash';
  static const OTP = '/otp';
  static const PHONE_ONBOARDING = '/phone-onboarding';
  static const CREATE_PIN = '/create-pin';
  static const PERSONAL_INFO = '/personal-info';
  static const SIGNIN_WITH_PIN = '/signin-with-pin';
  static const FORGET_PASSWORD = '/forget-password';
  static const HOBBIES_ONBOARDING = '/hobbies-onboarding';
  static const BRANDS_ONBOARDING = '/brands-onboarding';
  static const RETAILERS_ONBOARDING = '/retailers-onboarding';
  static const STYLE_ONBOARDING = '/style-onboarding';
  static const CHAT = '/chat';
  static const MY_DASHBOARD = '/my-dashboard';
  static const VISION_BOARD = '/vision-board';
  static const PROJECTS = '/projects';
  static const PROJECT_DETAIL = '/project-detail';
  static const PROFILE = '/profile';
  static const NAVBAR = '/navbar';
  static const NEW_PROJECT = '/new-project';
  static const CONTACT_US = '/contact-us';
  static const ACTIVITY = '/activity';
  static const HISTORY = '/history';
  static const ACCOUNT_SETTING = '/account-setting';
  static const NOTIFICATIONS = '/notifications';
  static const TOOL_AND_SUPPLY = '/tool-and-supply';
  static const PURCHASES = '/purchases';
  static const SEARCH_RESULT = '/search-result';
  static const TOOLS_AND_SUPPLIES_LIST = '/tools-and-supplies-list';
  static const VENDOR_LIST = '/vendor-list';
  static const PROJECT_INDIVIDUAL = '/project-individual';
  static const ONBOARDING_SUMMARY = '/onboarding-summary';
  static const PREFERENCES = '/preferences';
  static const SIGNUP_SUCCESS = '/signup-success';
  static const CHANGE_PIN = '/change-pin';
  static const TOOLS_AND_TUTORIALS = '/tools-and-tutorials';
  static const INDIVIDUAL_TOOL = '/individual-tool';
  static const SELECT_LANGUAGE = '/select-language';
  static const END_USER_LICENSE = '/end-user-license';
  static const PRIVACY_POLICY = '/privacy-policy';
  static const PROJECT_STATUS = '/project-status';
  static const CHANGE_LANGUAGE = '/change-language';
  static const CHANGE_COUNTRY = '/change-country';
  static const UPDATE_PIN = '/update-pin';
  static const ORDER_DETAILS = '/order-details';
  static const DISPATCHERS_LIST = '/dispatchers-list';
  static const CHAT_ROOM = '/chat-room';
  static const SIGNUP = '/signup';
  static const VERIFY_NFC = '/verify-nfc';
  static const ONBOARDING = '/onboarding';
}
